# Generated by Django 4.1.2 on 2022-10-10 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0007_alter_cart_id_alter_cartitem_cart_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["user__first_name", "user__last_name"]},
        ),
        migrations.RemoveField(model_name="customer", name="email",),
        migrations.RemoveField(model_name="customer", name="first_name",),
        migrations.RemoveField(model_name="customer", name="last_name",),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                # to='core.user'
            ),
            preserve_default=False,
        ),
    ]
