# Generated by Django 4.1.2 on 2022-10-14 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_order_options_alter_customer_birth_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can view history")],
            },
        ),
    ]
