# Generated by Django 4.1.2 on 2022-10-14 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_customer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["user__first_name", "user__last_name"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "permissions": [
                    ("cancel_order", "Can cancel order"),
                    ("view_history", "Can view history"),
                ]
            },
        ),
    ]
