# Generated by Django 4.1.2 on 2022-10-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_customer_options_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can view history")],
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
